services:
  mysql:
    image: mysql:8.0-bookworm
    environment:
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=redmine_production
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - /srv/docker/redmine/mysql:/var/lib/mysql
    # https://www.redmine.org/projects/redmine/wiki/MySQL_configuration
    command: --transaction-isolation=READ-COMMITTED
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  redmine:
    build: ./
    image: sameersbn/redmine:6.0.5
    depends_on:
      - mysql
    environment:
      - TZ=Asia/Kolkata

      - DB_ADAPTER=mysql2
      - DB_ENCODING=utf8mb4
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production

      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - NGINX_MAX_UPLOAD_SIZE=20m

      - SMTP_ENABLED=false
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

    healthcheck:
      test: curl -f http://localhost/up || exit 1
      interval: 10s
      timeout: 10s
      retries: 3

    ports:
      - "10083:80"
    volumes:
      - /srv/docker/redmine/redmine_mysql:/home/redmine/data
      - /srv/docker/redmine/redmine-logs:/var/log/redmine
